name: 'Commit Diff'
description: 'Fetch Commit Diff'
inputs:
  github-token:
    description: 'Passing GITHUB_TOKEN'
    required: true
outputs:
  diffs:
    description: 'Commit diff string'
  diffsJSON:
    description: 'Commit diff in JSON format'
runs:
  using: 'node16'
  main: 'index.js'
